### ISSUE TITLE
Nutzeranforderungen in ein Usecase-Diagramm einarbeiten

### ISSUE THREAD

**Issue by 31101** [max-eich/SE-Projekt#14]
Bitte das Zieldokument durchlesen und die Ziele in ein grobes Usecase-Diagramm eintragen.

**Comment by 31101** [comment]
Nutzeranforderungen sind im Use Case Diagramm eingearbeitet. Bitte Überprüfen.
@FappingAngel @Jonabcd1234 @salkiniuspopeye

**Comment by Theimbold** [comment]
@31101 Muss der Techniker sich nicht anmelden mit einem extra Techniker Konto ?
In Stammdaten Patient.docx steht, dass die Pflege:
**R/W bei Anamnese (Größe und Gewicht)** beim **Rest(Behinderung...) nur R**

Pfeil von Pflege geht aber zu Medizinische Anamnese Lesen und Schreiben. Wieso ?

Der Admin Darf email, ID, name, vorname AUCH lesen ... Pfeil geht nur zu Adressdaten schreiben..

USW.... ist das beabsichtigt ? Wenn ja ists okay, oder soll ich das genauer ins Detail neu überarbeiten ?

**Comment by 31101** [comment]
@Theimbold Kommentar wurde eingearbeitet
