### ISSUE TITLE
Skizze

### ISSUE THREAD

**Issue by 31101** [max-eich/SE-Projekt#16]
@3301 Habe die Skizze um weitere Folien ergänzt, wäre cool wenn du dir diese einmal angucken könntest, und entweder durch kommentare in der word versuchst Änderungen anzumerken oder dass wir uns nochmal donnerstag drüber unterhalten und weitere skizzen machen.

Anhand der Ziele soll eine Skizze für die Oberfläche des Programmes erstellt werden. Ziel der Skizze ist es dem Kunde ein grobes Bild zu machen und mögliche Änderungen zu provozieren.

**Comment by 31101** [comment]
Es fehlen noch die Ansichten für die Patientendaten. Es wäre schön, wenn in der linken oberen Ecke das Logo steht, dann rechts daneben den Titel und unter den beiden links beginnend sollen die Tabs stehen.

**Comment by 31101** [comment]
Bitte das Beratungsprotokoll mit in die Skizze einarbeiten. Das Beratungsprotokoll liegt im Analyse-Ordner.

**Comment by Theimbold** [comment]
@31101 Die aktuellste Version ist online. Habe die Vorschläge von Max eingearbeitet und das Inhaltsverzeichnis aktualisiert.
