### ISSUE TITLE
Risikoanalyse

### ISSUE THREAD

**Issue by 31101** [max-eich/SE-Projekt#32]
Die Risikoanalyse wurde nicht fertig gestellt.

**Comment by 31101** [comment]
Ready for review. @FappingAngel  @Jonabcd1234  @salkiniuspopeye

**Comment by max-eich** [comment]
Von meiner Seite überprüft und keine direkten Einwände.
Weitere Überprüfung von @Jonabcd1234 und @Theimbold trotzdem gewünscht
