### ISSUE TITLE
Beratungsgesprächsprotokoll

### ISSUE THREAD

**Issue by 31101** [max-eich/SE-Projekt#34]

**Comment by 31101** [comment]
Bereit zu Review @Jonabcd1234 @FappingAngel @salkiniuspopeye

**Comment by max-eich** [comment]
Fragen: 
-Ist die Agenda nicht überflüssig, weil wir das Inhaltsverzeichnis haben?
-Ist der Punkt "2.	Vorstellung der bisher erarbeiteten Ziele und der „Stammdaten Patient.docx“ Datei" nicht die Agenda selber? Wenn ja, warum nicht umbenannt oder gekürzt, wenn nein, wo ist der Punkt?

**Comment by 31101** [comment]
Ist jetzt eingearbeitet. Da das ein Protokoll ist gibt es für das stattgefundene Meeting eine Agenda, welche nicht gleich das Inhaltsverzeichnis ist. Deswegen gibt es Punkte, die nicht wirklich was Aussagen, weil wir uns bei diesen mit anderen Dokumenten beschäftig haben und nichts neues zum festhalten in dem Protokoll entstanden ist.
